build-PreSignupTriggerLambda:
	pwd
	ls
	ls /home/runner/work/inventory-app/inventory-app/.aws-sam/build/PreSignupTriggerLambda
	ls ../
	mvn -f /home/runner/work/inventory-app/inventory-app/product/service/lambda-services/cognito/signup/pom.xml -q clean verify -Dnative -DskipTests