AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Quarkus - quarkus-amazon-lambda-common-deployment
Parameters:
  TenantName:
    Type: String
    MinLength: 3
    MaxLength: 63
    #AllowedPattern: ^[a-z0-9](?:[a-z0-9\-]{0,61}[a-z0-9])?$
    Description: Enter a string. Must be alpha numeric 3-63 in length.
    Default: "minka-cloud" #"minka.tech" #
Resources:
  Signup:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub ${AWS::StackName}-Signup-Native-${AWS::Region}-${TenantName}
      Handler: not.used.in.provided.runtime
      Runtime: provided
      CodeUri: ../product/service/lambda-services/cognito/signup/target/function.zip
      MemorySize: 128
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 15

      Environment:
        Variables:
          DISABLE_SIGNAL_HANDLERS: true

Outputs:
    Signup:
        Description: Signup Lambda Function ARN
        Value: !GetAtt Signup.Arn
