on: [push]
jobs:
  native_build:
    runs-on: ubuntu-latest
    name: Build native Quarkus app
    steps:
      - name: Checkout the code
        uses: actions/checkout@master
      - name: Config graalvm
        uses: graalvm/setup-graalvm@v1
        with:
            version: 'latest'
            java-version: '17'
            components: 'native-image'
      - name: Install quarkus cli
        run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install quarkusio/tap/quarkus
      - name: Maven Clean and Verify
        run: |
          quarkus build --native --no-tests -Dquarkus.native.container-build=true
      - name: Upload native executable
        uses: actions/upload-artifact@v2
        with:
          name: function
          path: target/function.zip
