on: [push]
jobs:
  native_build:
    runs-on: ubuntu-latest
    name: Build native Quarkus app
    steps:
      - name: Checkout the code
        uses: actions/checkout@master
      - name: Config graalvm
        uses: graalvm/setup-graalvm@v1
        with:
            version: 'latest'
            java-version: '17'
            components: 'native-image'
      - name: Install quarkus cli
        run: |
          curl -Ls https://sh.jbang.dev | bash -s - trust add https://repo1.maven.org/maven2/io/quarkus/quarkus-cli/
          curl -Ls https://sh.jbang.dev | bash -s - app install --fresh --force quarkus@quarkusio
      - name: Maven Clean and Verify
        run: |
          quarkus build --native --no-tests -Dquarkus.native.container-build=true
      - name: Upload native executable
        uses: actions/upload-artifact@v2
        with:
          name: function
          path: target/function.zip
