name: Build And Run Unit Tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
      - name: Install docker
        run: brew install docker 
      - name: Maven Clean and Verify
        run: mvn -e clean verify -Pnative --define quarkus.native.container-build=true
      - name: Upload native executable
        uses: actions/upload-artifact@v2
        with:
          name: native-executable
          path: target/function.zip
