on: [push]

jobs:
  native_build:
    runs-on: macos-12
    name: Build native Quarkus app
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout the code
        uses: actions/checkout@master
      - name: Config graalvm
        uses: graalvm/setup-graalvm@v1
        with:
            version: 'latest'
            java-version: '17'
            components: 'native-image'
      - name: Maven Clean and Verify
        run: |
          mvn -q clean verify -Pnative
      - name: Upload native executable
        uses: actions/upload-artifact@v2
        with:
          name: function
          path: target/function.zip
