name: GraalVM Community Edition build
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image,llvm,llvm-toolchain'
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Show variables
        run: |
          echo "GRAALVM_HOME: $GRAALVM_HOME"
          echo "JAVA_HOME: $JAVA_HOME"
          java --version
          gu --version
          native-image --version
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4
        with:
          maven-version: '3.8.1'
      - name: Build with Maven
        run: |
          mvn clean install -q -Dnative -DskipTests
          ls target
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: function
          path: target/function.zip
          if-no-files-found: error