on: [push]
jobs:
  native_build:
    runs-on: ubuntu-latest
    name: Build native Quarkus app
    steps:
      - name: Checkout the code
        uses: actions/checkout@master
      - name: Config graalvm
        uses: graalvm/setup-graalvm@v1
        with:
            version: 'latest'
            java-version: '17'
            components: 'native-image'
      - name: Set up Homebrew
        id: set-up-homebrew
        uses: Homebrew/actions/setup-homebrew@master
      - name: Maven Clean and Verify
        run: |
          mvn clean verify -Dnative -DskipTests
          sam local invoke --template target/sam.native.yaml --event payload.json
      - name: Upload native executable
        uses: actions/upload-artifact@v2
        with:
          name: function
          path: target/function.zip
