on: [push]
jobs:
  native_build:
    runs-on: ubuntu-latest
    name: Build native Quarkus app
    steps:
      - uses: actions/labeler@v4
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Checkout the code
        uses: actions/checkout@master
      - name: Config graalvm
        uses: graalvm/setup-graalvm@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
            version: 'latest'
            java-version: '17'
            components: 'native-image'
      - name: Maven Clean and Verify
        env:
            GITHUB_TOKEN: ${{ github.token }}
        run: |
          mvn install -q -Dnative -DskipTests -Dquarkus.native.container-build=true

      - name: Upload native executable
        uses: actions/upload-artifact@v2
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          name: function
          path: target/function.zip
